spring.application.name=test_api

spring.datasource.url=jdbc:postgresql://dpg-d7lh1f9j2pic73f26nf0-a.oregon-postgres.render.com:5432/generatex?sslmode=require

spring.datasource.username=generatex_user
spring.datasource.password=2Pah4fQiU6PlLK0pnVc7sZbQ1Dcy0xTU

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true